# Site settings
title: Karim Hamidou
email: dontspam@khamidou.com
description: "My blog. I mostly talk about design and solving problems with software."
baseurl: ""
url: "http://khamidou.com"
github_username: khamidou
permalink: none
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
