# Site settings
title: Karim Hamidou
email: dontspam@khamidou.com
description: "My blog. I mostly talk about solving problems with software, devops and, occasionally, security."
baseurl: "/"
url: "http://khamidou.com"
github_username: khamidou

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
